name: Java CI with Maven

on:
  push:
    branches: master

env:
  DAY_OF_WEEK: Monday

jobs:
   build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          distribution: 'adopt'
          cache: maven
      - name: Maven Package
        run: mvn clean install
      
      - name : upload artifacts
        uses: actions/upload-artifact@v1
        with:
            name: artifacts
            path: expensemanager-backend/**

     

     

      - name: Present Working Directory
        run:  echo ${{ github.repository }}

     
           

      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
           aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
           aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
           aws-region: "us-east-1"
      
      - name: Remove S3 content
        run: aws s3 rm --recursive s3://expensemanager-frontendtest